### ISSUE TITLE
[Feature Request] New player macro's in their own folders

### ISSUE THREAD

**Issue by maxobremer** [esheyw/macro-creation-tweaks#1]
It would be nice if you could make it so that macro's created by a player are automatically put in a folder for each player.

**Comment by esheyw** [comment]
This is actually something I have setup at home kinda jankily and hardcoded for my players. I'll look into generalizing it and adding it.

**Comment by esheyw** [comment]
Implemented in 1.1.0. Let me know how it works for you and/or if you find any bugs!
