### ISSUE TITLE
Doesn't Work for Me Foundry V11

### ISSUE THREAD

**Issue by pesky-wobbit** [esheyw/macro-creation-tweaks#2]
FYI. Tried with all my normal modules, and also with just this one, but either way, this module has no effect for me.
New macro still defaults to chat.
No renaming.
No settings to adjust.

**Comment by esheyw** [comment]
There isn't really enough information to work with here. Foundry version? system? system version? any errors in the console?

**Comment by pesky-wobbit** [comment]
foundry v11.315
dnd5e v2.41
console errors show up on a refresh when module is activated:
![image](https://github.com/esheyw/macro-creation-tweaks/assets/477446/c566a360-ce86-4e00-aa2b-f08324712474)

**Comment by esheyw** [comment]
Ah, yea, this was being hidden by my dev environment, this should be fixed in 1.1.0.
