### ISSUE TITLE
[Bug] Sort Existing Macros button not working

### ISSUE THREAD

**Issue by maxobremer** [esheyw/macro-creation-tweaks#3]
When i try to use the sort existing macro button i get the following error:
![image](https://github.com/esheyw/macro-creation-tweaks/assets/86924581/42810a6a-f0e8-40ce-a848-3bdd03dce41d)

If it matters, these are my settings for the module:
![image](https://github.com/esheyw/macro-creation-tweaks/assets/86924581/53ea1be6-b298-4640-8e97-bf42c7472ad6)

**Comment by esheyw** [comment]
Check added; Full handling for unauthored macros will take more effort to do nicely than I'm gonna put in until there's been some refactoring elsewhere, so for now it just yells a bit in the console but otherwise sorts. Gonna hope this was an isolated case.
